# Generated by Django 5.0.13 on 2025-05-18 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layout", models.JSONField(default=dict)),
                ("visible_widgets", models.JSONField(default=list)),
                ("date_range", models.CharField(default="last_week", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("USER", "Utilisateur"),
                            ("EMPLOYEE", "Employé"),
                            ("ATTESTATION", "Attestation de travail"),
                            ("MISSION", "Ordre de mission"),
                            ("SYSTEM", "Système"),
                        ],
                        max_length=15,
                    ),
                ),
                ("content_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action_type"], name="dashboard_a_action__8d7a03_idx"
                    ),
                    models.Index(
                        fields=["content_type"], name="dashboard_a_content_22f9a0_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="dashboard_a_user_id_fab5dd_idx",
                    ),
                ],
            },
        ),
    ]
